name: form_handling
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: "^3.6.1"

dependencies:
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lint: ^2.3.0

flutter:
